# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4234af203b791e01b1493368da932fdea243ede19ae9befdf7cbbbb8e5e350a247397efe7be028be145b679f5f03b87a918c8c18b56868055dd48cc1c116a299

test:
  secret_key_base: d5bb1a42b6b2e7e37634a94d74992f48b2f2fc56ab08a5f35803bcb4c2412da348f8ae180fdbda0b69e38bd091863c6ff9ca12b0fe86a4aa33f13c19c061a418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
